.TH tmx "1" "March 2015" "Version 0.1" "User Commands"
.SH NAME
tmx \- open tmux sessions efficiently.
.SH SYNOPSIS
.B tmx 
\fISESSION\fR
.SH DESCRIPTION
Launch a new tmux window each time you open a terminal window. 
.sp
Inactive tmux windows are purged on EXIT pseudo-signal.
.SH AUTHOR
Written by Rainer Borene.
.SH "REPORTING BUGS"
Please file bugs at https://github.com/rainerborene/tmx/issues/
.SH SEE ALSO
.BR tmux(1)
